name: lua

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  style:
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
          version: "0.20.0"
      - uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: "18"
          check-path: lua

  test:
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: luajit-openresty

      - name: Build extension (release)
        run: |
          pushd lua/wincent/commandt/lib
          make
          popd

      - name: Run unit tests (release)
        run: bin/test

      - name: Run stress tests (release, benchmarks)
        run: TIMES=1 bin/benchmarks/matcher.lua

      # Repeat the tests in DEBUG mode (ie. with `assert()` calls active).
      - name: Build extension (debug)
        run: |
          pushd lua/wincent/commandt/lib
          DEBUG=1 make
          popd

      - name: Run unit tests (debug)
        run: bin/test

      - name: Run stress tests (debug, benchmarks)
        run: TIMES=1 bin/benchmarks/matcher.lua
